---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rstp/public_html/rstp.unm.edu/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp .env.example $DEPLOYPATH.env
    - /usr/local/cpanel/3rdparty/bin/git --git-dir=$DEPLOYPATH.git --work-tree=$DEPLOYPATH checkout -f
    - /usr/local/cpanel/3rdparty/bin/git --git-dir=$DEPLOYPATH.git --work-tree=$DEPLOYPATH pull origin main
    - /usr/local/bin/php $DEPLOYPATH/artisan migrate --force
    - /usr/local/bin/php $DEPLOYPATH/artisan config:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan route:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan migrate --force
